# nfpm example config file
#
# check https://nfpm.goreleaser.com/configuration for detailed usage
#
name: "<name>"
arch: amd64
platform: linux
version: "<version>"
##section: "default"
#priority: "extra"
#replaces:
#- foobar
#provides:
#- sber
#depends:
#- foo
#- bar
#recommends:
#- whatever
#suggests:
#- something-else
#conflicts:
#- not-foo
#- not-bar
maintainer: "Pavel Fiskovich"
description: Crispy DUMMY service
vendor: Sber
#homepage: "http://example.com"
license: "MIT?"
#changelog: "changelog.yaml"
depends:
- ipvsadm
rpm:
  arch: "x86_64"
overrides:
  rpm:
    contents:
      - dst: /opt/crispy/dummy
        type: dir

      - src: "<artifacts>/dummy"
        dst: /opt/crispy/dummy/dummy

      - src: "<rpm>/dummy.yaml"
        dst: /opt/crispy/dummy/dummy.yaml
        type: config

      - src: "<rpm>/crispy-dummy.service"
        dst: /lib/systemd/system/crispy-dummy.service

      - dst: /var/run/crispy-dummy.sock
        type: ghost

    scripts:
      preinstall:  "<rpm>/preinstall.sh"
      postinstall: "<rpm>/postinstall.sh"
      preremove:   "<rpm>/preremove.sh"
      postremove:  "<rpm>/postremove.sh"
